### ISSUE TITLE
Uint Serialize impl does not skip leading zeros

### ISSUE THREAD

**Issue by mattsse** [recmo/uint#224]
**Version**
List the versions of the service you are using. The easiest way to get
this information is using the `cargo tree` subcommand:

ruint v1.7.0

**Description**

The Serialize impl of `Uint` is not compliant with the ethereum rpc quantity format: https://ethereum.org/en/developers/docs/apis/json-rpc/#quantities-encoding

I tried this code:

```rust

let val = serde_json::to_string(&U256::ZERO).unwrap();
// `0x0000000000000000000000000000000000000000000000000000000000000000`
```

I expected to see this happen:

quantity format requires this to be `0x0`

Ideally the Serialize impl of `Uint` would skip leading zeros. This is also how primitive-types::U256 is serialized: https://github.com/paritytech/parity-common/blob/master/primitive-types/impls/serde/src/serialize.rs#L21

**Comment by recmo** [comment]
Thanks for opening this issue. I think the way ethereum rpc specs things is reasonable. But there are other places where full bits padded to next byte boundary is required.

I think a good middle ground is to have `Uint` trim leading zeros and have `Bits` uses the byte-padded form.
