### ISSUE TITLE
B192 is using 256 bits in the definition.

### ISSUE THREAD

**Issue by Kuly14** [recmo/uint#230]
**Version**
1.7.0

**Description**

https://github.com/recmo/uint/blob/main/src/aliases.rs#L53 

The B192 and U192 are constructed with 256 bits and only three limbs:
```rust
alias! {
    U192 B192 (256, 3);
}
```
According to the readme:

```md
[Uint] will panic! if you try to construct it with incorrect arguments. 
```
Not sure if this is a bug or I'm missing something.

**Comment by prestwich** [comment]
closed by #234
