### ISSUE TITLE
unused allocation in `from_base_le`

### ISSUE THREAD

**Issue by DaniPopes** [recmo/uint#254]
https://github.com/recmo/uint/blob/192e5f5d5ec792383ec298fcae60a8d957edfb65/src/base_convert.rs#L67-L73

Unsure if the iterator was supposed to be reversed before collecting, but as it is right now the allocation is completely useless.

**Comment by prestwich** [comment]
Closing as fixed in #255

**Comment by DaniPopes** [comment]
Only part is fixed, the method still allocates when it could be avoided
