### ISSUE TITLE
Current macro definition is not easily re-exportable

### ISSUE THREAD

**Issue by ralexstokes** [recmo/uint#307]
Refer this line:
https://github.com/recmo/uint/blob/da9f1a4fea350c958ab6bd8bb11aa84fbdda05be/ruint-macro/src/lib.rs#L49

The use of `::ruint` means that re-export (e.g. [here](https://github.com/alloy-rs/core/blob/main/crates/primitives/src/lib.rs#L55)) breaks unless the user of the re-exported macro _also_ has `ruint` in their top-level module hierarchy (which suggests they need to add to `Cargo.toml` and breaks the point of the re-export).

I'm opening this issue to discuss possible fixes. I haven't verified this but I think just using `$crate::` in lieu of `::ruint` will fit the bill (cf. https://doc.rust-lang.org/1.5.0/book/macros.html#the-variable-crate). Otherwise I think `ruint` by itself would also work as then we could just `use re_exporter::{ruint, uint};` (which is not as nice but is better IMO than adding the explicit `ruint` dependency and possible in `alloy_primitives`).

If we find a solution we like, I'm happy to open a PR.

**Comment by gakonst** [comment]
@DaniPopes cc

**Comment by prestwich** [comment]
> I'm opening this issue to discuss possible fixes. I haven't verified this but I think just using $crate:: in lieu of ::ruint will fit the bill (cf. https://doc.rust-lang.org/1.5.0/book/macros.html#the-variable-crate). 

The specal `$crate` variable only works in declarative macros, while the `uint!` macro is a procedural macro. So it's not as simple as swapping it out. The proc macro is effectively codegen. We have to design some clean code that achieves this

It seems bad for the `ruint-macro` crate to get a redesign to support sideloading the `ruint` types that it relies on from other crates.

In the meantime, adding `ruint` to your dependencies is the correct workaround, and we'll document this workaround in the primitives library
