### ISSUE TITLE
`try_from_be_slice` returns `Some`  for array of length 33

### ISSUE THREAD

**Issue by agostbiro** [recmo/uint#339]
**Version**
v1.10.1

**Platform**

Darwin <REDACTED> 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64

**Description**

I noticed that `try_from_be_slice` returns `Some`  for an array of zeroes with length 33.

I tried this code:

`assert!(U256::try_from_be_slice(&[0; 33]).is_none());`

I expected to see this happen: the assertion should succeed.

Instead, this happened: the assertion fails.

Note that the following assertion succeeds:

`assert!(U256::try_from_be_slice(&[1; 33]).is_none());`

I'm happy to submit a fix if you confirm the bug.

**Comment by prestwich** [comment]
This is expected behavior. As the docs note, [`Uint::try_from_be_slice`](https://docs.rs/ruint/latest/ruint/struct.Uint.html#method.try_from_be_slice) accepts slices of any length, so long as the uint that the BE slice represents will fit in the `Uint`

**Comment by agostbiro** [comment]
Ok, thanks!
