### ISSUE TITLE
Do not 0 pad on debug and hex formatting

### ISSUE THREAD

**Issue by onbjerg** [recmo/uint#346]
**Is your feature request related to a problem? Please describe.**

Currently ruint types add leading 0s in the debug and hex formatting impls, but Rust's own primitive types do not do this.

If you want leading zeros, you can use the padding built in to the Rust formatter

**Describe the solution you'd like**

Remove leading zeros

**Comment by gakonst** [comment]
@recmo wdyt here? we're happy to fix

**Comment by prestwich** [comment]
related, padding directives are not currently supported
https://github.com/recmo/uint/issues/295
