### ISSUE TITLE
1.12.0 introduced a bug in `uint!`

### ISSUE THREAD

**Issue by ewoolsey** [recmo/uint#359]
**Version**
1.12.0

**Platform**
Darwin Erics-MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

❯ rustc --version
rustc 1.76.0 (07dca489a 2024-02-04)

**Description**
This code used to compile on 1.11 and no longer compiles on 1.12.0

```rust
uint! {
    pub const A: [U256; 2] = [
        0x00006f85d6f68a85ec10345351a23a3aaf07f38af8c952a7bceca70bd2af7ad5_U256,
        0x00004b4110c9ae997782e1509b1d0fdb20a7c02bbd8bea7305462b9f8125b1e8_U256,
    ];
}
```

**Error Message**
```
error: macros that expand to items must be delimited with braces or followed by a semicolon
   --> src/poseidon/constants.rs:3:1
    |
3   | / uint! {
4   | |
5   | | pub const A: [U256; 2] = [
6   | |     [
...   |
490 | |
491 | | }
    | |_^
    |
    = note: this error originates in the macro `uint` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by ewoolsey** [comment]
Amazing thanks! When do you think we can expect a patch release for this?

**Comment by DaniPopes** [comment]
[1.12.1](https://crates.io/crates/ruint/1.12.1) was released with the fix for this included. Thanks for reporting!
